### ISSUE TITLE
头像上传出错，是必须要用upyun么？

### ISSUE THREAD

**Issue by lifeidle** [ego008/gae-bbs#2]
用管理员账号登陆后，必须首先上传头像图片。报500错，应该是我没有设置好upyun的账户关系。

`The server is temporary error now. 500
Traceback (most recent call last): File "/base/data/home/apps/n~gaegaebbs/1.414328003629720207/yui.py", line 1461, in __call__ handler.post(*groups, **groupdict) File "/base/data/home/apps/n~gaegaebbs/1.414328003629720207/view.py", line 171, in post avatar = u.writeFile( file_path_name, img_large, True) File "/base/data/home/apps/n~gaegaebbs/1.414328003629720207/upyun.py", line 157, in writeFile resp = self._net_worker('PUT',DL+self.bucket+DL+path, data,headers,metadata) File "/base/data/home/apps/n~gaegaebbs/1.414328003629720207/upyun.py", line 228, in _net_worker resp = connection.getresponse() File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_dist/lib/python2.7/gae_override/httplib.py", line 526, in getresponse raise HTTPException(str(e)) HTTPException: Deadline exceeded while waiting for HTTP response from URL: http://v0.api.upyun.com/saespot//avatar/life.jpg
`

不知老大能否改回到原来saespot版直接gae上传图片的机制？
万分感谢！

**Comment by ego008** [comment]
是用又拍云，难得改了

**Comment by lifeidle** [comment]
老大，是不是只需要购买upyun的“存储服务”就行了？

存储服务
0.0043 元/GB¥ 0元/日 ≈ ¥ 0 / 月
按照每日 CDN 流量使用，实行 1:1 的每日存储空间使用量免费。
